name: svg_optimizer
description: A Dart package that optimizes SVG files at build time using SVGO.
repository: https://github.com/DroidsOnRoids/svg-optimizer
issue_tracker: https://github.com/DroidsOnRoids/svg-optimizer/issues
version: 0.0.2+1

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0
  yaml_edit: ^2.2.1
  collection: ^1.18.0
  posix: ^6.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

screenshots:
  - description: The svg_optimizer package logo.
    path: screenshots/logo.png
